name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Adjust the Node.js version as needed

      - name: Run the app
        run: npm run app.js  # Replace "start" with the appropriate npm script

      - name: Run tests (if present)
        run: npm test --if-present


